### PR TITLE
order_fill modified

### PR DESCRIPTION
**Pull request by Atmabuddy99**

### CODE REVIEW

**Comment by uberdeveloper** [comment]
Average price for side=1 seems inconsistent
```python
depth = dict(bid=
    [
        dict(price=101,quantity=20,count=6),
        dict(price=100,quantity=15,count=6),
        dict(price=99,quantity=30,count=6), 
    ],                                     
    ask= [
        dict(price=102,quantity=20,count=6),
        dict(price=103,quantity=15,count=6),
        dict(price=104,quantity=30,count=6),
    ]                                       
    )
print ("side=1")
print("="*60)
print("Average price = ", order_fill_price(1,depth,10,'bid','ask'))
print("Average price = ", order_fill_price(1,depth,50,'bid','ask'))
print("Average price = ", order_fill_price(1,depth,100,'bid','ask'))
print("Average price = ", order_fill_price(1,depth,150,'bid','ask'))
print("Average price = ", order_fill_price(1,depth,167,'bid','ask'))
print("Average price = ", order_fill_price(1,depth,220,'bid','ask'))
print('-'*60)

print ("side=0")
print("="*60)
print("Average price = ", order_fill_price(0,depth,10,'bid','ask'))
print("Average price = ", order_fill_price(0,depth,50,'bid','ask'))
print("Average price = ", order_fill_price(0,depth,100,'bid','ask'))
print("Average price = ", order_fill_price(0,depth,150,'bid','ask'))
print("Average price = ", order_fill_price(0,depth,167,'bid','ask'))
print("Average price = ", order_fill_price(0,depth,220,'bid','ask'))
```

**Comment by Atmabuddy99** [comment]
the method used for calculting this is exponential if the quantity exceeds the depth quantity 

:initial_price -which is the first level of depth
spread-abs(initial-final )price in the levels
n-exponential
formula =(intialprice+spread*n)+ min(depthtotalqty,remaining of the traded qty)

**Comment by uberdeveloper** [comment]
> the method used for calculting this is exponential if the quantity exceeds the depth quantity
> 
> :initial_price -which is the first level of depth spread-abs(initial-final )price in the levels n-exponential formula =(intialprice+spread*n)+ min(depthtotalqty,remaining of the traded qty)

price = `initial_price + spread**n`
so if price = 100, spread=3, leg1 = 100+*3**1, leg2 = 100+3**2`

**Comment by Atmabuddy99** [comment]
leg 1 should also be multplied with the qty ryt?

**Comment by Atmabuddy99** [comment]
place change "value" to "ivalue" in the recursive function
everything is working as expected if u just change that
if remaining_qty>0:
            "value"=total_traded_value(s,intialprice,spread,remaining_qty,add_on,n,ivalue,vos)
that value needs to be changed as "ivalue

**Comment by Atmabuddy99** [comment]
or change the last few lines as this  post ivalue
tto=ivalue
n=n*2
if remaining_qty<=0:
      return tto
  else:
      return total_traded_value(s,intialprice,spread,remaining_qty,add_on,n,ivalue,vos)

both these methods work as expected

**Comment by uberdeveloper** [comment]
```python
depth = dict(bid=
    [
     dict(price=101,quantity=10,count=6),
     dict(price=100,quantity=10,count=6),
     dict(price=99,quantity=10,count=6),
    ],
    ask= [
     dict(price=102,quantity=10,count=6),
     dict(price=103,quantity=10,count=6),
     dict(price=104,quantity=10,count=6),
    ]
)
>>> order_fill_price(1,depth,60,'bid','ask')
>>> 105.5
```

**Comment by Atmabuddy99** [comment]
its 102+2*2 which would be 106
next would be 102+2*4
next 102+2*8

**Comment by uberdeveloper** [comment]
> its 102+2_2 which would be 106 next would be 102+2_4 next 102+2*8

Exactly should be 104.5, but result is 105.5
Am I missing something here?

**Comment by uberdeveloper** [comment]
Calculation looks fine

**Comment by uberdeveloper** [comment]
`order_fill_price(1, depth,300000,'bid','ask')`
throws recursion error
could you handle this exception?

**Comment by uberdeveloper** [comment]
Handle case where depth of either side is zero

**Comment by uberdeveloper** [comment]
```python
from fastbt.utils import *
depth = dict(bid=
    [
        dict(price=101,quantity=20,count=6),
        dict(price=100,quantity=15,count=6),
        dict(price=99,quantity=30,count=6), 
    ],                                     
    ask= [
        dict(price=102,quantity=20,count=6),
        dict(price=103,quantity=15,count=6),
        dict(price=104,quantity=30,count=6),
    ]                                       
    )
o_fill_price(1,depth,15,'bid','ask')
```

raises the following error

UnboundLocalError                         Traceback (most recent call last)
Cell In[1], line 14
      1 from fastbt.utils import *
      2 depth = dict(bid=
      3     [
      4         dict(price=101,quantity=20,count=6),
   (...)
     12     ]                                       
     13     )
---> 14 o_fill_price(1,depth,15,'bid','ask')

File ~/fastbt/src/fastbt/utils.py:837, in o_fill_price(side_, market_depth, quantity, bid, ask)
    835             ivalue=ivalue+u
    836             n=n+1       
--> 837 ttv=(value+ivalue)/quantity
    838 return ttv

UnboundLocalError: local variable 'ivalue' referenced before assignment
```

**Comment by uberdeveloper** [comment]
```python
from fastbt.utils import *
depth = dict(bid=
    [
        dict(price=101,quantity=20,count=6),
        dict(price=100,quantity=15,count=6),
        dict(price=99,quantity=30,count=6), 
    ],                                     
    ask= [
        dict(price=102,quantity=20,count=6),
        dict(price=103,quantity=15,count=6),
        dict(price=104,quantity=30,count=6),
    ]                                       
    )
o_fill_price(1,depth,15,'bid','ask')
```
raises the following error

```
UnboundLocalError                         Traceback (most recent call last)
Cell In[1], line 14
      1 from fastbt.utils import *
      2 depth = dict(bid=
      3     [
      4         dict(price=101,quantity=20,count=6),
   (...)
     12     ]                                       
     13     )
---> 14 o_fill_price(1,depth,15,'bid','ask')

File ~/fastbt/src/fastbt/utils.py:837, in o_fill_price(side_, market_depth, quantity, bid, ask)
    835             ivalue=ivalue+u
    836             n=n+1       
--> 837 ttv=(value+ivalue)/quantity
    838 return ttv

UnboundLocalError: local variable 'ivalue' referenced before assignment
```

**Review by uberdeveloper — APPROVED** [review]

**Pull request merged**
